export class playerInfo{
    uId
    playerName
    playerOpenId
    picUrl
    showPicUrl
    teamId
    teamName
    character
    isFiring
    bHasDied
    location
    health
    healthMax
    liveState
    killNum
    killNumBeforeDie
    playerKey
    gotAirDropNum
    maxKillDistance
    damage
    killNumInVehicle
    killNumByGrenade
    rank
    isOutsideBlueCircle
    inDamage
    heal
    headShotNum
    survivalTime
    driveDistance
    marchDistance
    assists
    outsideBlueCircleTime
    knockouts
    rescueTimes
    useSmokeGrenadeNum
    useFragGrenadeNum
    useBurnGrenadeNum
    useFlashGrenadeNum
}